name       : bitcoin
version    : 0.13.2
release    : 10
source     :
    - https://github.com/bitcoin/bitcoin/archive/v0.13.2.tar.gz : 8a1307605b71b1df720ed0360d801d8939138aaca0a495d0f1e4e500efc2eaa1
license    : MIT
summary    : Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world.
description: |
    Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world.
component  : network.clients
clang      : no
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - db4.8-devel
    - libboost-devel
setup      : |
    ./autogen.sh
    %configure --disable-static --with-gui=qt5
build      : |
    %make
install    : |
    %make_install
    install -Dm644 %workdir%/contrib/debian/bitcoin-qt.desktop %installroot%/usr/share/applications/bitcoin-qt.desktop
    install -Dm644 $pkgfiles/bitcoin128.png %installroot%/usr/share/pixmaps/bitcoin128.png
    # Confs and Man for bitcoind and cli
    install -Dm644 %workdir%/contrib/debian/examples/bitcoin.conf %installroot%/usr/share/doc/bitcoind/examples/bitcoin.conf
    install -Dm644 %workdir%/contrib/debian/bitcoind.bash-completion %installroot%/usr/share/bash-completion/completions/bitcoind
    install -Dm644 %workdir%/contrib/debian/manpages/bitcoin-cli.1 %installroot%/usr/share/man/man1/bitcoin-cli.1
    install -Dm644 %workdir%/contrib/debian/manpages/bitcoin-qt.1 %installroot%/usr/share/man/man1/bitcoin-qt.1
    install -Dm644 %workdir%/contrib/debian/manpages/bitcoind.1 %installroot%/usr/share/man/man1/bitcoind.1
    install -Dm644 %workdir%/contrib/debian/manpages/bitcoin.conf.5 %installroot%/usr/share/man/man5/bitcoin.conf.5
