name       : bitcoin
version    : 0.20.0
release    : 38
source     :
    - https://github.com/bitcoin/bitcoin/archive/v0.20.0.tar.gz : ec5a2358ee868d845115dc4fc3ed631ff063c57d5e0a713562d083c5c45efb28
license    : MIT
summary    : Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world
description: |
    Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world.
component  : network.clients
clang      : no
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(libzmq)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - db4.8-devel
    - libboost-devel
setup      : |
    %autogen --disable-static --enable-hardening --with-gui=qt5
build      : |
    BITCOIN_GENBUILD_NO_GIT=1 %make
install    : |
    %make_install
    install -Dm0644 $pkgfiles/bitcoin-qt.desktop $installdir/usr/share/applications/bitcoin-qt.desktop
    install -Dm0644 $pkgfiles/bitcoin128.png $installdir/usr/share/pixmaps/bitcoin128.png
    # Confs and Man for bitcoind and cli
    install -Dm0644 $pkgfiles/bitcoin.conf $installdir/usr/share/doc/bitcoind/examples/bitcoin.conf
    install -Dm0644 $pkgfiles/bitcoind.bash-completion $installdir/usr/share/bash-completion/completions/bitcoind
