name       : bitcoin
version    : 0.15.0.1
release    : 17
source     :
    - https://github.com/bitcoin/bitcoin/archive/v0.15.0.1.tar.gz : a2d28632be6918ce23d2fd589f0aecbb2a90579c9345f47fdfe1e77ec31f023e
license    : MIT
summary    : Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world.
description: |
    Bitcoin is an experimental new digital currency that enables instant payments to anyone, anywhere in the world.
component  : network.clients
clang      : no
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - db4.8-devel
    - libboost-devel
setup      : |
    %autogen --disable-static --enable-hardening --with-gui=qt5
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $workdir/contrib/debian/bitcoin-qt.desktop $installdir/usr/share/applications/bitcoin-qt.desktop
    install -Dm644 $pkgfiles/bitcoin128.png $installdir/usr/share/pixmaps/bitcoin128.png
    # Confs and Man for bitcoind and cli
    install -Dm644 $workdir/contrib/debian/examples/bitcoin.conf $installdir/usr/share/doc/bitcoind/examples/bitcoin.conf
    install -Dm644 $workdir/contrib/debian/bitcoind.bash-completion $installdir/usr/share/bash-completion/completions/bitcoind
